#!groovy
def FRONTEND_DIR = 'frontend/project-board-app'
def FRONTEND_ENVIRONMENTS_DIR = 'frontend/project-board-app/src/environments/'
def DOCKER_ARTIFACT_DIR = 'dist/project-board-app'

pipeline {

    agent any

    tools {
        nodejs '10.14.2'
    }

    stages {
        stage('Checkout') {
            steps {
              checkout scm
            }
        }

        stage('Replace environment') {
            steps {
                dir(FRONTEND_ENVIRONMENTS_DIR) {
                    writeFile file: "environment.prod.ts", text: env.ENV_PROD_TS
                }
            }
        }

        stage('Build Artifacts') {

            steps {
                dir(FRONTEND_DIR) {

                    sh 'npm install @angular/cli'
                    sh 'npm install yarn'
                    sh './node_modules/yarn/bin/yarn install'
                    sh './node_modules/@angular/cli/bin/ng build --prod'

                    dir(DOCKER_ARTIFACT_DIR) {
                        stash includes: '**/*', name: 'dockerArtifacts'
                    }
                }
            }

        }

        stage('Docker Build') {
            agent {
                label 'docker'
            }

            steps {
                dir(FRONTEND_DIR) {

                    dir(DOCKER_ARTIFACT_DIR) {
                        unstash 'dockerArtifacts'
                    }

                    sh 'sudo docker build -t pb-frontend .'
                    sh 'sudo docker save pb-frontend -o pb-frontend.tar'
                    sh 'sudo chmod 777 pb-frontend.tar'

                    sshagent(['jenkins-username-ssh-key']) {
                        sh 'scp -o StrictHostKeyChecking=no pb-frontend.tar jenkins@$REMOTE_HOST:~'
                    }
                }
            }

        }
    }

}
