#!groovy
def BACKEND_DIR = 'backend/project-board'
def DOCKER_ARTIFACT_DIR = 'docker/temp'

pipeline {

    agent any

    tools {
        gradle '5.0'
        jdk 'JDK-11.0.1 (OpenJDK)'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test') {

            steps {
                dir(BACKEND_DIR) {
                    sh 'gradle clean test jacocoTestReport'
                    jacoco buildOverBuild: true, classPattern: '**/classes', deltaBranchCoverage: '5', execPattern: '**/**.exec', sourceInclusionPattern: '**/*.java', sourcePattern: '**/src/main/java'
                }
            }

        }

        stage('Build Artifacts') {
            environment {
                JIRA_CREDS = credentials('jira-creds')
                LDAP_CREDS = credentials('ldap-creds')
                DATA_SRC_CREDS = credentials('data-src-creds')
                MAIL_CREDS = credentials('mail-creds')
            }

            steps {
                dir(BACKEND_DIR) {
                    sh 'gradle dockerCopy'

                    dir(DOCKER_ARTIFACT_DIR) {
                        stash includes: '*', name: 'dockerArtifacts'
                    }
                }
            }
        }

        stage('Build Docker Image') {
            agent {
                label 'docker'
            }

            steps {
                dir(DOCKER_ARTIFACT_DIR) {
                    unstash 'dockerArtifacts'

                    sh 'sudo docker build -t pb_backend .'
                    sh 'sudo docker save pb_backend -o pb_backend.tar'
                    sh 'sudo chmod 777 pb_backend.tar'

                    sshagent(['jenkins-username-ssh-key']) {
                        sh 'scp -o StrictHostKeyChecking=no pb_backend.tar jenkins@$REMOTE_HOST:~'
                    }
                }
            }
        }

    }

}
