-- Requires Users.sql to be executed first

INSERT INTO ORG_STRUCTURE (ID, USER_ID, USER_MANAGER_ID, MANAGING_USER) VALUES
(1, 'User1', 'User2', 1);

INSERT INTO ORG_STRUCTURE_STAFF (ORG_STRUCTURE_ID, STAFF_USER_ID) VALUES
(1, 'User3'),
(1, 'User4');
